<a href="https://colab.research.google.com/github/theyuvrajtayal21-design/100-day-bootcamp/blob/main/Student_Test_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning Assessment – Student Copy
## Practical Exam | Data Cleaning with Pandas

**Instructions:**
1. Read each section carefully and complete the missing code cells.
2. Perform data cleaning step-by-step without skipping validation steps.
3. Ensure the final cleaned DataFrame is assigned to `clean_df` and exported as `clean_student_data_80k.csv`.

---

### Step 1: Import Libraries and Load Dataset
- Load `messy_student_data_80k.csv` into a pandas DataFrame named `df`.
- Inspect the first 10 rows and check the dataset shape.

In [ ]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv('/content/messy_student_data_80k (1).csv')
print('Dataset Shape:', df.shape)
df.head(10)

Dataset Shape: (48484, 13)

,student_id,student_name,email,age,gender,city,department,course,marks,annual_salary,phone,admission_date,Email_address
0,STU-770487,Vihaan Chauhan,pooja.rao802@yahoo.com,20.0,m,Unknown,ds,mtech,50.0,600000.0,6.225065e+09,NaN,NaN
1,STU-356787,Rohan Chauhan,pooja.chauhan958@gmail.com,19.0,unknown,Hyderabad,information technology,btech,75.5,1200000.0,7.219982e+09,2024-02-20,NaN
2,STU-334053,Karan Chauhan,rohan.mehta301@example.com,18.0,unknown,Bengaluru,mechanical,btech,82.0,350000.0,9.620276e+09,2023-09-01,NaN
3,STU-246316,Kavya Kumar,aditya.jain838@gmail.com,23.0,o,Gurgaon,unknown,bca,82.0,600000.0,6.801080e+09,NaN,NaN
4,STU-872246,Kabir Patel,ishita.kumar54@gmail.com,21.0,unknown,Gurgaon,unknown,mtech,50.0,600000.0,8.472708e+09,2023-01-10,NaN
5,STU-809570,Diya Sharma,neha.chauhan547@outlook.com,18.0,unknown,Unknown,information technology,mtech,65.0,600000.0,9.375422e+09,2022-08-15,NaN
6,STU-671858,Kavya Singh,rahul.rao87@outlook.com,22.0,m,PUNE,electronics,mtech,75.5,350000.0,9.559061e+09,2021-12-31,NaN
7,STU-191161,Sneha Jain,karan.jain18@yahoo.com,19.0,m,Chennai,ds,mtech,82.0,0.0,9.554762e+09,2022-08-15,NaN
8,STU-719176,Ananya Yadav,pooja.malhotra446@example.com,19.0,unknown,Unknown,unknown,bca,88.5,600000.0,6.376846e+09,2022-08-15,NaN
9,STU-542417,Vihaan Rao,aarav.tiwari188@outlook.com,19.0,o,Gurugram,mechanical,b.sc,75.5,800000.0,7.434057e+09,2024-02-20,NaN

In [ ]:
df.head()

,student_id,student_name,email,age,gender,city,department,course,marks,annual_salary,phone,admission_date,Email_address
0,STU-770487,Vihaan Chauhan,pooja.rao802@yahoo.com,20.0,m,Unknown,ds,mtech,50.0,600000.0,6.225065e+09,NaN,NaN
1,STU-356787,Rohan Chauhan,pooja.chauhan958@gmail.com,19.0,unknown,Hyderabad,information technology,btech,75.5,1200000.0,7.219982e+09,2024-02-20,NaN
2,STU-334053,Karan Chauhan,rohan.mehta301@example.com,18.0,unknown,Bengaluru,mechanical,btech,82.0,350000.0,9.620276e+09,2023-09-01,NaN
3,STU-246316,Kavya Kumar,aditya.jain838@gmail.com,23.0,o,Gurgaon,unknown,bca,82.0,600000.0,6.801080e+09,NaN,NaN
4,STU-872246,Kabir Patel,ishita.kumar54@gmail.com,21.0,unknown,Gurgaon,unknown,mtech,50.0,600000.0,8.472708e+09,2023-01-10,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48484 entries, 0 to 48483
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      48484 non-null  object
 1   student_name    48484 non-null  object
 2   email           48484 non-null  object
 3   age             48484 non-null  float64
 4   gender          48484 non-null  object
 5   city            48484 non-null  object
 6   department      48484 non-null  object
 7   course          48484 non-null  object
 8   marks           48484 non-null  float64
 9   annual_salary   48484 non-null  float64
 10  phone           44817 non-null  float64
 11  admission_date  36330 non-null  object
 12  Email_address   0 non-null      float64
dtypes: float64(5), object(8)
memory usage: 4.8+ MB

In [ ]:
df.describe()

                age         marks  annual_salary         phone  Email_address
count  48484.000000  48484.000000   4.848400e+04  4.481700e+04            0.0
mean      20.218381     71.968332   5.757054e+05  8.110201e+09            NaN
std        1.608404     15.119432   3.233416e+05  1.176535e+09            NaN
min       18.000000     45.000000   0.000000e+00  6.100106e+09            NaN
25%       19.000000     65.000000   3.500000e+05  7.133269e+09            NaN
50%       20.000000     75.500000   6.000000e+05  8.163613e+09            NaN
75%       21.000000     82.000000   8.000000e+05  9.187308e+09            NaN
max       24.000000     91.400000   1.200000e+06  1.000000e+10            NaN

### Step 2: Standardize Column Names
Rename columns to snake_case:
`student_id`, `student_name`, `email`, `age`, `gender`, `city`, `department`, `course`, `marks`, `annual_salary`, `phone`, `admission_date`

In [ ]:
# TODO: Rename columns
df.rename(columns={
    'Student ID': 'student_id',
    'Full Name': 'student_name',
    'Contact Email': 'email',
    'Age': 'age',
    'Gender': 'gender',
    "City": "city",
    "Department": "department",
    "Degree Course": "course",
    "Marks Percentage": "marks",
    "Annual Package": "annual_salary",
    "Mobile Number": "phone",
    "Enrollment Date": "admission_date"
}, inplace=True)
df.columns

Index(['student_id', 'student_name', 'email', 'age', 'gender', 'city',
       'department', 'course', 'marks', 'annual_salary', 'phone',
       'admission_date', 'Email_address'],
      dtype='object')

### Step 3: Handle Missing Values & Placeholders
- Replace placeholders (`'NA'`, `'N/A'`, `'null'`, `'Not Available'`, `'unknown'`) with `np.nan`.
- Impute categorical columns with `'Unknown'`.
- Impute missing numeric values using column medians.

In [ ]:
missing_count = df.isna().sum()
print(missing_count)
# TODO: Replace string placeholders with NaN
missing_values = ['NA', 'N/A', 'null', 'Not Available', 'unknown']
df.replace(missing_values, np.nan , inplace=True)

for column in df.columns:
    if df[column].dtype == 'object':
        df[column].fillna('Unknown', inplace=True)
# TODO: Impute categorical & numeric missing values
df["age"] = pd.to_numeric(df["age"], errors='coerce')
df["annual_salary"] = pd.to_numeric(df["annual_salary"], errors='coerce')
df["marks"] = pd.to_numeric(df["marks"], errors='coerce')
catagorical_columns = ["student_name", "email", "course"]
numeric_columns = ["age", "annual_salary", "marks","gender"]

df["age"].fillna(df["age"].median(), inplace=True)
df["annual_salary"].fillna(df["annual_salary"].median(), inplace=True)
df["marks"].fillna(df["marks"].median(), inplace=True)

student_id            0
student_name          0
email                 0
age                   0
gender                0
city                  0
department            0
course                0
marks                 0
annual_salary         0
phone              3667
admission_date    12154
Email_address     48484
dtype: int64

/tmp/ipykernel_1267/1230427613.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna('Unknown', inplace=True)
/tmp/ipykernel_1267/1230427613.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].median(), inplace=True)
/tmp/ipykernel_1267/1230427613.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["annual_salary"].fillna(df["annual_salary"].median(), inplace=True)
/tmp/ipykernel_1267/1230427613.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["marks"].fillna(df["marks"].median(), inplace=True)

### Step 4: Text Cleaning & Category Standardization
- Strip whitespaces.
- Standardize: `bangalore` -> `bengaluru`, `gurgaon` -> `gurugram`.
- Standardize departments (`computer science` -> `cse`, etc.).
- Standardize degree courses (`btech`, `mtech`, `bca`, `bsc`).

In [ ]:
df["course"].unique()

array(['mtech', 'btech', 'bca', 'b.sc'], dtype=object)

In [ ]:
# TODO: Clean and standardize text columns
df["city"] = df["city"].str.strip()
df["city"] = df["city"].replace({
    "bangalore": "bengaluru",
    "gurgaon": "gurugram"})
df["department"] = df["department"].str.strip()
df["department"] = df["department"].str.lower()
df["department"] = df["department"].replace({
    "Computer Science":"cse",
    "Information Technology":"it",
    "Mechanaical Engineering":"me",
    "Data Science":"ds",
    "Electronics":"ece",
    "data science": "ds",
})

df["gender"] = df["gender"].str.strip()
df["gender"] = df["gender"].str.lower()
df["gender"] = df["gender"].replace({
    'Male':"m",
    'male':"m",
   'Female':"f",
    'other':"o",
    'FEMALE':"o",
    'female':"o",
   'Other':"o",
    'MALE':"m"

})

df["course"] = df["course"].str.strip()
df["course"] = df["course"].str.lower()
df["course"] = df["course"].replace({
    'MTECH':"mtech",
    'B.Sc':"bsc",
    'm.tech':"mtech",
    'bca':'bca',
    'BTECH':'btech',
    'B.Tech':'btech','BCA':'bca',
    'M.Tech':'btech',
    'b.tech':'btech',

})

### Step 5: Remove Duplicates
- Identify and drop duplicate rows.

In [ ]:
# TODO: Count and drop duplicate rows
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

### Step 6: Validate Numeric Boundaries & Outliers
- `age`: 17 to 35
- `marks`: 0 to 100
- `annual_salary`: > 0 and < 10,000,000

In [ ]:
# TODO: Fix invalid numeric ranges and fill with median
df=df[df['age'].between(17,35)]
df=df[df['marks'].between(0,100)]
df=df[df['annual_salary'].between(0,10000000)]

### Step 7: Email & Phone Validation
- Validate email pattern.
- Clean phone numbers (10 digits starting with 6-9).

In [ ]:
# TODO: Validate emails and clean mobile numbers
df["phone"] = df["phone"].astype("string").str.replace(r"\D","",regex=True)
invalid_phone = ~df["phone"].str.match(r"[6-9]\d{9}$",na=False)
print("Invalid phone:",invalid_phone.sum())
df.loc[invalid_phone , "phone"] = np.nan


df["email"]=df["email"].str.strip().str.lower()

invalid_email = ~df["email"].str.match(r"^[^\s@]+@[^\s@]+\.[^\s@]+$", na=False)
print("Invalid Emails:", invalid_email.sum())

df.loc[invalid_email, "Email_address"]=np.nan

Invalid phone: 48484
Invalid Emails: 1452

### Step 8: Parse Dates & Export
- Convert `admission_date` to datetime.
- Export final cleaned DataFrame to `clean_student_data_80k.csv`.

In [ ]:
df["admission_date"] = pd.to_datetime(df["admission_date"],errors = "coerce",dayfirst = True)
clean_df = df.copy()
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48484 entries, 0 to 48483
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      48484 non-null  object
 1   student_name    48484 non-null  object
 2   email           48484 non-null  object
 3   age             48484 non-null  float64
 4   gender          48484 non-null  object
 5   city            48484 non-null  object
 6   department      48484 non-null  object
 7   course          48484 non-null  object
 8   marks           48484 non-null  float64
 9   annual_salary   48484 non-null  float64
 10  phone           0 non-null      string
 11  admission_date  36330 non-null  datetime64[ns]
 12  Email_address   0 non-null      float64
dtypes: datetime64[ns](1), float64(4), object(7), string(1)
memory usage: 4.8+ MB

/tmp/ipykernel_1267/421008639.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["admission_date"] = pd.to_datetime(df["admission_date"],errors = "coerce",dayfirst = True)

In [ ]:
clean_df = df.copy()
clean_df.to_csv('/content/messy_student_data_80k (1).csv', index=False)
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48484 entries, 0 to 48483
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      48484 non-null  object
 1   student_name    48484 non-null  object
 2   email           48484 non-null  object
 3   age             48484 non-null  float64
 4   gender          48484 non-null  object
 5   city            48484 non-null  object
 6   department      48484 non-null  object
 7   course          48484 non-null  object
 8   marks           48484 non-null  float64
 9   annual_salary   48484 non-null  float64
 10  phone           0 non-null      string
 11  admission_date  36330 non-null  datetime64[ns]
 12  Email_address   0 non-null      float64
dtypes: datetime64[ns](1), float64(4), object(7), string(1)
memory usage: 4.8+ MB